# Appveyor Behavior Config
pull_requests:
  do_not_increment_build_number: true

# Appveyor Build Config
image:
  - Visual Studio 2017

platform:
  - x86
  - x64

init:
  - choco upgrade cmake							            # Upgrade CMake
  - set path=C:\Program Files\CMake\bin;%path%	# Add it to the path

before_build:
  - mkdir build && cd build
  - cmake -G "%GENERATOR%" -DOPENSSL_ROOT_DIR="%OPENSSL_DIR%" ..


environment:
  matrix: # Generate all possible combinations of the following environment variables
    - GENERATOR: "Visual Studio 15 2017"
      OPENSSL_DIR: "C:/OpenSSL-v11-Win32"
    - GENERATOR: "Visual Studio 15 2017 Win64"
      OPENSSL_DIR: "C:/OpenSSL-v11-Win64"

matrix:
  exclude: # Don't generate builds with this specific combination of environment variables
    - platform: x64
      GENERATOR: "Visual Studio 15 2017"
      OPENSSL_DIR: "C:/OpenSSL-v11-Win64"

    - platform: x86
      GENERATOR: "Visual Studio 15 2017 Win64"
      OPENSSL_DIR: "C:/OpenSSL-v11-Win32"


# version: 0.60.0.{build}.{branch}

# configuration:
#   - Release
# platform:
#   - x64
#   - Win32
# environment:
#   matrix:
#   - archi: Win64
#   - archi:
# matrix:
#   exclude:
#     - platform: x64
#       archi:
#     - platform: Win32
#       archi: Win64
# clone_folder: C:\etterna

# cache:
#   - C:\ProgramData\chocolatey\bin -> appveyor.yml
#   - C:\ProgramData\chocolatey\lib -> appveyor.yml

# artifacts:
# - path: Etterna *.exe

# install:
# - cmd: choco install nsis.portable

# init:
# - set arch=
# - if "%archi%"=="Win64" ( set arch= Win64)
# - echo %arch%
# - echo %APPVEYOR_BUILD_WORKER_IMAGE%
# - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
# - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
# - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
# - echo %generator%

# before_build:
# - cmd: git submodule update --init --recursive
# - cmd: >-

#     mkdir build && cd build

#     "C:\Program Files (x86)\cmake\bin\cmake" .. -G %generator%

#     del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

# build:
#   project: C:\etterna\build\Etterna.sln
#   verbosity: normal
#   parallel: true

# after_build:
# - cmd: >-

#     "C:\Program Files (x86)\NSIS\makensis.exe" "C:\etterna\stepmania.nsi"

# - cmd: >-
#     rename "C:\etterna\Etterna *.exe" "Etterna *-%appveyor_build_version%.exe"

# notifications:
# - provider: Email
#   to:
#   - etternadev@gmail.com
#   on_build_success: false
#   on_build_failure: true
#   on_build_status_changed: true

# deploy:
#   provider: Environment
#   name: etterna
#   on:
#     branch: master
#     image: Visual Studio 2017
#     configuration: Release

# #for:
# #
# # override settings for `master` branch
# #-
# #  branches:
# #    only:
# #      - master
# #
# #  image:
# #    - Visual Studio 2013
# #    - Visual Studio 2015
# #    - Visual Studio 2017
# #  configuration:
# #    - Release
# #    - RelWithDebInfo
