language: cpp
dist: xenial
sudo: required

git:
  depth: false

# Path is modified here since we install CMake to the /usr/local/ prefix. Usually the system
# would check the full path until it reached CMake, but Travis specifically adds their CMake
# version to their path. We want our CMake to have priority, so we add it to the start of the 
# search path. 
env:
  matrix:
    - PATH=/usr/local/bin:${PATH}
  # COVERITY_SCAN_TOKEN
  global:
    - secure: "dqRcKvhvVSV0+M9UuLTJvns4aFKHGdl7O2Bu5OkCt6hy2Fx6RErfNZKIhwoiIFSWbrLN5rbjiSrEttpGQR5lGBc3POxgW+578Ty7a8HUO5EMtXB5x4pFa8cWqkUe4xwX1tAZvHRZYpGutBwFDwLf2r6/RMZBV+FxwnjDOhpsFkIo7oIHo7qReeFoW5JkAYGOle+ZUyjjU/li/7svyO7dUmifQcdB3CQ8bMgF3Jyu8+HTzutsLep1rSN7vsw2X/NET+cvnqJ5fC//6B9stBcp80g5I3TMgx4w372VJ9Yn/Co/rqpkQ3toit+1KhJ39Wm3IaQiKctfeyvl1Wa8TDJqvmQxj/fsz+3Co+j0Afx0fW6IuF7i0aH0qJEH9sVohspyEdirlVc+QCaI2wBz06FaWZ9nIIy5fssRIzelf7MbjBHDD3iQU9TqeFZ+u4r30hUwRv1xrhpHg7f0zun0zQv29tfrroZTJQtBrCy8vscqIsP8GWPZeig/fW1Mn0vvCbI0Z7anmICYPjLWQDHjSVKexdWvmtux76PPIRlMB7FlQbQY5aar4olaSI8eFvLKV8/RUXICD36m+RNP1LXKhqJWmuvco88e+YUclvhYH+QAAqWN5f7qq4o0ujxeZvsQqYb9T5NEW+Wsap/g5RqX7S2D3XonNTGW3k14PEzdrpVVXfc="

matrix:
  include:

    ##### Linux ##################
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc

    ##### macOS ##################
    - os: osx
      osx_image: xcode10.1
      install:
        - sudo gem install xcpretty
      script:
        - mkdir -p ${TRAVIS_BUILD_DIR}/build && cd ${TRAVIS_BUILD_DIR}/build
        - cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -G "Xcode" ..
        - set -o pipefail && xcodebuild ARCHS="x86_64" -project Etterna.xcodeproj -target Etterna -destination 'platform=OSX,arch=x86_64' -configuration Release | xcpretty

# This will only run for the linux builds
# The other os's have overridden the script tag
script:
  - sh .ci/build.sh
  - mkdir -p ${TRAVIS_BUILD_DIR}/build && cd ${TRAVIS_BUILD_DIR}/build
  - cmake -G "Ninja" ..
  - ninja

addons:
  coverity_scan:
    project:
      name: etternagame/etterna
      description: "Advanced cross-platform rhythm game focused on keyboard play"
    notification_email: etternadev@gmail.com
    build_command_prepend: "sh .ci/build.sh; mkdir -p ${TRAVIS_BUILD_DIR}/build && cd ${TRAVIS_BUILD_DIR}/build; cmake .."
    build_command: "make -j 4"
    branch_pattern: coverity_scan
  homebrew:
    packages:
      - openssl
      - cmake
      - nasm
    update: true
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - nasm
      - libudev-dev
      - gcc-5
      - g++-5
      - libgtk2.0-dev
      - binutils-dev
      - libasound-dev
      - libpulse-dev
      - libjack-dev
      - libc6-dev
      - libogg-dev
      - libvorbis-dev
      - libxtst-dev
      - libxrandr-dev
      - libglew-dev
      - libuv-dev
      - clang-format-5.0
      - ninja-build
    update: true

# Deploy to Github Release when tag is pushed
before_deploy:
  - cd ${TRAVIS_BUILD_DIR}/build/ && cpack
deploy:
  file: ${TRAVIS_BUILD_DIR}/build/*.dmg
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx
  provider: releases
  draft: true
  api_key:
    secure: "OaNlihwLKYCt3pTQYtnz5aKZQAnHbiKT0I2D7Muwzr0QS7c+3JI0+nRk+aytD3pm3qJ2ZbaHGxWBIyvahmWrKw1UynhKCNbXTVSyqhciLNF5JFURdttvo4s5zqzJ8CEJCgZii1Fev/VmvxXSPICnXhE7IvA5Ad2TUGlxuhajlSC/ilHz8kcuBVyzPBAWUHrRNq4atv9O32dSFgnk6Iy1aOO63UzargVVP7G61DP42wX6JBx6i3LxXO6NU8ehJsCY+voBczVLj3FvT+6prfjxVbIZbUO616V/o2KVHJIznNJIHfytozokyAzk96dnS3b/rUPhboA3PTGIrsKjmh6JzPo/3+o6wR90RK5MNLTLrPWmrKN6sndcwtYrEx+Lqv21hsG4mLk828bPXYVJC9qQFRvk47PQHhp9M+VsoGSNFDPfcrIVlOHZh/S5zW36/ZtSjRbBIBcCZ7mnkA+kUXP811fSgvcguCX67a6DhJyzGvjEC3ezvkVr7GoLzg+fXkz01OLG/bvRn6FG6/sY7TPQGeB/BwHloMR6yV+RN+PYVBJtwzMQmXPhN1ft6WUdvpE4SF5HEVS50wx+uAdE+awpCTeIdwdMldyyjnl7r3vk+683KQ+d6mXQjggUDNxOXZ5lxD7xiBCVZrK3dAvtaCooT9RYFYvdiDHC3DvNJiguM9I="