version: 5.0.12.{build}.{branch}
pull_requests:
  do_not_increment_build_number: true
image:
  - Visual Studio 2015
  - Visual Studio 2017
configuration: Release
clone_folder: C:\etterna

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

artifacts:
- path: Etterna *.exe
  
install:
- cmd: choco install nsis.portable

before_build:
- cmd: git submodule update --init --recursive
- cmd: >-
    
    mkdir build && cd build

    "C:\Program Files (x86)\cmake\bin\cmake" .. -G "Visual Studio 14 2015"

    del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

build:
  project: C:\etterna\build\Etterna.sln
  verbosity: normal

after_build:
- cmd: >-
    
    "C:\Program Files (x86)\NSIS\makensis.exe" "C:\etterna\stepmania.nsi"
- cmd: >-
    
    "C:\Program Files (x86)\NSIS\makensis.exe" /DSongless "C:\etterna\stepmania.nsi"

notifications:
- provider: Email
  to:
  - etternadevs@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
