blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Contact us on the Etterna Dev Group Discord
    url: https://discord.gg/ZqpUjsJ
    about: Join the EDG Discord for support and discussion with the devs.